#Application Url

baseUrl = https://www.way2automation.com/angularjs-protractor/banking/#/login

#Browser Configuration
browser = chrome

#Credentials


#Implicit Wait (in seconds)
implicitWait = 10

#Explicit Wait (in seconds)
explicitWait = 30